"""Database and vector index layer for Photo Brain."""

from .indexer import index_photo
from .location import (
    LocationResolverConfig,
    assign_user_location,
    resolve_photo_location,
    upsert_user_location,
)
from .face_grouping import (
    accept_face_group,
    list_face_group_proposals,
    rebuild_face_group_proposals,
    reject_face_group,
)
from .records import (
    build_photo_record,
    list_face_identities,
    list_face_previews,
    list_persons,
    load_photo_record,
)
from .schema import (
    Base,
    ClassificationRow,
    ExifDataRow,
    FaceDetectionRow,
    FacePersonLinkRow,
    FaceIdentityRow,
    FaceGroupProposalRow,
    FaceGroupProposalMemberRow,
    PersonRow,
    LocationLabelRow,
    MemoryEventRow,
    PhotoFileRow,
    PhotoLocationRow,
    TextEmbeddingRow,
    VisionDescriptionRow,
    create_engine_from_url,
    event_photos,
    init_db,
    session_factory,
)
from .updates import assign_face_identity, merge_persons, rename_person, set_photo_user_context
from .vector_backend import PgVectorBackend

__all__ = [
    "Base",
    "ClassificationRow",
    "ExifDataRow",
    "assign_face_identity",
    "merge_persons",
    "rename_person",
    "FaceDetectionRow",
    "FaceIdentityRow",
    "FacePersonLinkRow",
    "FaceGroupProposalRow",
    "FaceGroupProposalMemberRow",
    "PersonRow",
    "LocationLabelRow",
    "MemoryEventRow",
    "PhotoFileRow",
    "PhotoLocationRow",
    "TextEmbeddingRow",
    "VisionDescriptionRow",
    "build_photo_record",
    "index_photo",
    "list_face_identities",
    "list_face_previews",
    "list_persons",
    "load_photo_record",
    "resolve_photo_location",
    "assign_user_location",
    "rename_person",
    "merge_persons",
    "set_photo_user_context",
    "rebuild_face_group_proposals",
    "list_face_group_proposals",
    "accept_face_group",
    "reject_face_group",
    "PgVectorBackend",
    "LocationResolverConfig",
    "upsert_user_location",
    "create_engine_from_url",
    "event_photos",
    "init_db",
    "session_factory",
]
